kind: Service
apiVersion: v1
metadata:
  labels:
    app: sami-kube-maat
  name: sami-kube-maat
  namespace: workshop

spec:
  type: NodePort
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: sami-kube-maat